t = int(input("Valor para tabuada : "))
print ("A tabuada de {} x 1 e {}".format(t,t*1))
print ("A tabuada de {} x 2 e {}".format(t,t*2))
print ("A tabuada de {} x 3 e {}".format(t,t*3))
print ("A tabuada de {} x 4 e {}".format(t,t*4))
print ("A tabuada de {} x 5 e {}".format(t,t*5))
print ("A tabuada de {} x 6 e {}".format(t,t*6))
print ("A tabuada de {} x 7 e {}".format(t,t*7))
print ("A tabuada de {} x 8 e {}".format(t,t*8))
print ("A tabuada de {} x 9 e {}".format(t,t*9))
print ("A tabuada de {} x 10 e {}".format(t,t*10))