v = int(input('O valor a ser lido com intuito de saber os resultados e : '))
v1 = (v*2)
v2 = (v*3)
v3 = (v**2)
print ('O dobro do valor e {:-^10}\nO triplo do valor e {:-^10}\nSua raiz quadrade e {:-^10}'.format(v1,v2,v3))